# Generated by Django 5.1.6 on 2025-03-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfIncome',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
