# Generated by Django 5.1.6 on 2025-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_income_payment_method_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
