# Generated by Django 5.1.6 on 2025-03-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_income_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
