# Generated by Django 5.1.6 on 2025-03-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_budget'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_user_category_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_user_category_budget_month_year'),
        ),
    ]
