# Generated by Django 5.1.6 on 2025-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_budget_unique_user_category_budget_month_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_user_category_budget',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_user_category_budget_monthly'),
        ),
    ]
